pipeline{
    environment{

    }
    agent{
        docker {
            image 'abhishekf5/maven-abhishek-docker-agent:v1'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    
    stages{
        stage('Stage1'){
            sh 'ls -ltr'
                     
    }
    }
}