pipeline {
     environment {
        registry = "sanjaydas9027/currency-exchange"
        registryCredential = 'DOCKER_CRED'
        DOCKER_IMAGE = "${registry}:${BUILD_NUMBER}"
        SONAR_URL = "http://3.111.197.24:9000/"
    }
    
    agent {
        docker {
            image 'abhishekf5/maven-abhishek-docker-agent:v1'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    stages {
            stage('Static Code Analysis'){
            steps{
               withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
                    sh 'cd CurrencyExchange && mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'
                }
            }   
            }
            stage('Quality Gate') {
            steps {
                script {
                    def qg = waitForQualityGate abortPipeline: false, credentialsId: 'sonarqube'
                    if (qg.status != 'OK') {
                        error "Quality Gate did not pass"
                    }
                }
            }
            }
        stage('Build') {
            steps {
                // List files in the workspace
                sh 'ls -ltr'

                // Replace this with your actual Maven build steps
                sh 'cd CurrencyExchange && mvn clean package'
            }
        }
        stage('Debug') {
            steps {
                sh 'pwd'
                sh 'ls -la'
            }
        }


        stage('Build and Push Docker Image') {
            steps {
                script {
                    sh 'cd CurrencyExchange && ls -ltr && docker build -t ${DOCKER_IMAGE} .'
                    def dockerImage = docker.image("${DOCKER_IMAGE}")
                    docker.withRegistry('', registryCredential) {
                        dockerImage.push()
                    }
                }
            }
        }

        stage('Remove Unused docker image') {
            steps {
                    sh "docker rmi ${DOCKER_IMAGE}"
            }
        }
        
    }
    post {
        always {
            script {
                sh 'docker logout'
                def workspaceDir = "${JENKINS_HOME}/workspace/${JOB_NAME}"
                sh "rm -rf ${workspaceDir}"
            }
        }
    }





}
